// <auto-generated />
namespace Lesson_9_firstCode_AddTableKey.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class CreadBD : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreadBD));
        
        string IMigrationMetadata.Id
        {
            get { return "202606191609158_CreadBD"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
