//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson_7_DTB_ModelFist
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pictures
    {
        public int Id { get; set; }
        public int Customer_ID { get; set; }
        public string C_Name { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Customers Customers1 { get; set; }
    }
}
