//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson_7_DTB_ModelFist
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public int PositionID { get; set; }
        public string PositionName { get; set; }
    }
}
